FROM python:3.11-slim

WORKDIR /app

# matplotlib headless
ENV MPLBACKEND=Agg
ENV PYTHONUNBUFFERED=1

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app/

CMD ["python", "pv_planning.py"]
